**week 3 dataset-1**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dc = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas.csv")

dc.reset_index(drop=True,inplace=True)
dc.drop(columns=["Index"],inplace=True)
dc

     Age      Salary  Rating       Location  Established Easy Apply
0   44.0   $44k-$99k     5.4       India,In         1999       TRUE
1   66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2    NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3   64.0   $44k-$99k     4.4       India In         1988         -1
4   25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5   44.0   $77k-$89k     1.4       India,In         1999       TRUE
6   21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7   44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8   35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9   22.0   $44k-$99k     7.7       India,In           -1       TRUE
10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11  44.0   $10k-$49k     6.7       India,In         2009         -1
12   NaN   $44k-$99k     0.0       India,In         1999         -1
13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16  19.0   $19k-$40k     4.5       India,In         1984         -1
17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21  35.0   $44k-$99k     5.0    New York,Ny         1946         -1
22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24  13.0   $44k-$99k    -1.0    New York,Ny         1987         -1
25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27  52.0   $44k-$99k     5.4       India,In         1935         -1
28   NaN   $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
copy_data=dc.copy()

In [ ]:
#Missing Values
#7 rows in  age column
#1 row in rating column
dc.isnull().sum()

Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [ ]:
#Data Types
dc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          22 non-null     float64
 1   Salary       29 non-null     object
 2   Rating       28 non-null     float64
 3   Location     29 non-null     object
 4   Established  29 non-null     int64
 5   Easy Apply   29 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.5+ KB

In [ ]:
#converting column names

dc.columns=[x.lower() for x in dc.columns]
dc.columns=[x.replace(" ","_") for x in dc.columns]
dc

     age      salary  rating       location  established easy_apply
0   44.0   $44k-$99k     5.4       India,In         1999       TRUE
1   66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2    NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3   64.0   $44k-$99k     4.4       India In         1988         -1
4   25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5   44.0   $77k-$89k     1.4       India,In         1999       TRUE
6   21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7   44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8   35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9   22.0   $44k-$99k     7.7       India,In           -1       TRUE
10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11  44.0   $10k-$49k     6.7       India,In         2009         -1
12   NaN   $44k-$99k     0.0       India,In         1999         -1
13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16  19.0   $19k-$40k     4.5       India,In         1984         -1
17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21  35.0   $44k-$99k     5.0    New York,Ny         1946         -1
22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24  13.0   $44k-$99k    -1.0    New York,Ny         1987         -1
25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27  52.0   $44k-$99k     5.4       India,In         1935         -1
28   NaN   $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
#filling the missing values in age column with mean value(39)
#mean = 39
dc.age.fillna(dc.age.mean(),inplace=True)

dc["age"] =dc["age"].astype(int)
dc

    age      salary  rating       location  established easy_apply
0    44   $44k-$99k     5.4       India,In         1999       TRUE
1    66   $55k-$66k     3.5    New York,Ny         2002       TRUE
2    39   $77k-$89k    -1.0    New York,Ny           -1         -1
3    64   $44k-$99k     4.4       India In         1988         -1
4    25   $44k-$99k     6.4  Australia Aus         2002         -1
5    44   $77k-$89k     1.4       India,In         1999       TRUE
6    21   $44k-$99k     0.0    New York,Ny           -1         -1
7    44   $44k-$99k    -1.0  Australia Aus           -1         -1
8    35   $44k-$99k     5.4    New York,Ny           -1         -1
9    22   $44k-$99k     7.7       India,In           -1       TRUE
10   55   $10k-$49k     5.4       India,In         2008       TRUE
11   44   $10k-$49k     6.7       India,In         2009         -1
12   39   $44k-$99k     0.0       India,In         1999         -1
13   25   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14   66   $44k-$99k     4.0  Australia Aus         2020       TRUE
15   44  $88k-$101k     3.0  Australia Aus         1999         -1
16   19   $19k-$40k     4.5       India,In         1984         -1
17   39   $44k-$99k     5.3    New York,Ny         1943       TRUE
18   35   $44k-$99k     6.7    New York,Ny         1954       TRUE
19   32   $44k-$99k     3.3    New York,Ny         1955       TRUE
20   39   $44k-$99k     5.7    New York,Ny         1944       TRUE
21   35   $44k-$99k     5.0    New York,Ny         1946         -1
22   19   $55k-$66k     7.8    New York,Ny         1988       TRUE
23   39   $44k-$99k     2.4    New York,Ny         1999       TRUE
24   13   $44k-$99k    -1.0    New York,Ny         1987         -1
25   55   $44k-$99k     0.0  Australia Aus         1980       TRUE
26   39   $55k-$66k     NaN       India,In         1934       TRUE
27   52   $44k-$99k     5.4       India,In         1935         -1
28   39   $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
#Salary Formatting
#$ is removed
#salary in thousands(k)
dc.salary=[x.replace("$","") for x in dc.salary]
dc.salary=[x.replace("k","") for x in dc.salary]
dc

    age  salary  rating       location  established easy_apply
0    44   44-99     5.4       India,In         1999       TRUE
1    66   55-66     3.5    New York,Ny         2002       TRUE
2    39   77-89    -1.0    New York,Ny           -1         -1
3    64   44-99     4.4       India In         1988         -1
4    25   44-99     6.4  Australia Aus         2002         -1
5    44   77-89     1.4       India,In         1999       TRUE
6    21   44-99     0.0    New York,Ny           -1         -1
7    44   44-99    -1.0  Australia Aus           -1         -1
8    35   44-99     5.4    New York,Ny           -1         -1
9    22   44-99     7.7       India,In           -1       TRUE
10   55   10-49     5.4       India,In         2008       TRUE
11   44   10-49     6.7       India,In         2009         -1
12   39   44-99     0.0       India,In         1999         -1
13   25   44-99    -1.0  Australia Aus         2019       TRUE
14   66   44-99     4.0  Australia Aus         2020       TRUE
15   44  88-101     3.0  Australia Aus         1999         -1
16   19   19-40     4.5       India,In         1984         -1
17   39   44-99     5.3    New York,Ny         1943       TRUE
18   35   44-99     6.7    New York,Ny         1954       TRUE
19   32   44-99     3.3    New York,Ny         1955       TRUE
20   39   44-99     5.7    New York,Ny         1944       TRUE
21   35   44-99     5.0    New York,Ny         1946         -1
22   19   55-66     7.8    New York,Ny         1988       TRUE
23   39   44-99     2.4    New York,Ny         1999       TRUE
24   13   44-99    -1.0    New York,Ny         1987         -1
25   55   44-99     0.0  Australia Aus         1980       TRUE
26   39   55-66     NaN       India,In         1934       TRUE
27   52   44-99     5.4       India,In         1935         -1
28   39   39-88     3.4  Australia Aus         1932         -1

In [ ]:
#rating formatting
#converting nan to nil
#converting -1 to 0

dc.fillna({"rating":"Nil"},inplace=True)
dc["rating"] =dc["rating"].astype(str)

dc.rating=[x.replace("-1","0") for x in dc.rating]
dc

    age  salary rating       location  established easy_apply
0    44   44-99    5.4       India,In         1999       TRUE
1    66   55-66    3.5    New York,Ny         2002       TRUE
2    39   77-89    0.0    New York,Ny           -1         -1
3    64   44-99    4.4       India In         1988         -1
4    25   44-99    6.4  Australia Aus         2002         -1
5    44   77-89    1.4       India,In         1999       TRUE
6    21   44-99    0.0    New York,Ny           -1         -1
7    44   44-99    0.0  Australia Aus           -1         -1
8    35   44-99    5.4    New York,Ny           -1         -1
9    22   44-99    7.7       India,In           -1       TRUE
10   55   10-49    5.4       India,In         2008       TRUE
11   44   10-49    6.7       India,In         2009         -1
12   39   44-99    0.0       India,In         1999         -1
13   25   44-99    0.0  Australia Aus         2019       TRUE
14   66   44-99    4.0  Australia Aus         2020       TRUE
15   44  88-101    3.0  Australia Aus         1999         -1
16   19   19-40    4.5       India,In         1984         -1
17   39   44-99    5.3    New York,Ny         1943       TRUE
18   35   44-99    6.7    New York,Ny         1954       TRUE
19   32   44-99    3.3    New York,Ny         1955       TRUE
20   39   44-99    5.7    New York,Ny         1944       TRUE
21   35   44-99    5.0    New York,Ny         1946         -1
22   19   55-66    7.8    New York,Ny         1988       TRUE
23   39   44-99    2.4    New York,Ny         1999       TRUE
24   13   44-99    0.0    New York,Ny         1987         -1
25   55   44-99    0.0  Australia Aus         1980       TRUE
26   39   55-66    Nil       India,In         1934       TRUE
27   52   44-99    5.4       India,In         1935         -1
28   39   39-88    3.4  Australia Aus         1932         -1

dc["location"]=dc["location"].str.replace("India In","India")
dc["location"]=dc["location"].str.replace("IndiaIn","India")
dc["location"]=dc["location"].str.replace("New YorkNy","New York")
dc["location"]=dc["location"].str.replace("Australia Aus","Australia")
dc

In [ ]:
#location formatting
dc["location"].str.replace(",","").str.rstrip("In").str.rstrip("Ny").str.rstrip("Aus")

0          India
1       New York
2       New York
3         India
4     Australia
5          India
6       New York
7     Australia
8       New York
9          India
10         India
11         India
12         India
13    Australia
14    Australia
15    Australia
16         India
17      New York
18      New York
19      New York
20      New York
21      New York
22      New York
23      New York
24      New York
25    Australia
26         India
27         India
28    Australia
Name: location, dtype: object

In [ ]:
#established 	formatting
#replacing -1 with unknown
dc["established"] =dc["established"].astype(str)
dc.established=[x.replace("-1","Unknown") for x in dc.established]
dc

    age  salary rating       location established easy_apply
0    44   44-99    5.4       India,In        1999       TRUE
1    66   55-66    3.5    New York,Ny        2002       TRUE
2    39   77-89    0.0    New York,Ny     Unknown         -1
3    64   44-99    4.4       India In        1988         -1
4    25   44-99    6.4  Australia Aus        2002         -1
5    44   77-89    1.4       India,In        1999       TRUE
6    21   44-99    0.0    New York,Ny     Unknown         -1
7    44   44-99    0.0  Australia Aus     Unknown         -1
8    35   44-99    5.4    New York,Ny     Unknown         -1
9    22   44-99    7.7       India,In     Unknown       TRUE
10   55   10-49    5.4       India,In        2008       TRUE
11   44   10-49    6.7       India,In        2009         -1
12   39   44-99    0.0       India,In        1999         -1
13   25   44-99    0.0  Australia Aus        2019       TRUE
14   66   44-99    4.0  Australia Aus        2020       TRUE
15   44  88-101    3.0  Australia Aus        1999         -1
16   19   19-40    4.5       India,In        1984         -1
17   39   44-99    5.3    New York,Ny        1943       TRUE
18   35   44-99    6.7    New York,Ny        1954       TRUE
19   32   44-99    3.3    New York,Ny        1955       TRUE
20   39   44-99    5.7    New York,Ny        1944       TRUE
21   35   44-99    5.0    New York,Ny        1946         -1
22   19   55-66    7.8    New York,Ny        1988       TRUE
23   39   44-99    2.4    New York,Ny        1999       TRUE
24   13   44-99    0.0    New York,Ny        1987         -1
25   55   44-99    0.0  Australia Aus        1980       TRUE
26   39   55-66    Nil       India,In        1934       TRUE
27   52   44-99    5.4       India,In        1935         -1
28   39   39-88    3.4  Australia Aus        1932         -1

In [ ]:
#easy_apply formatting
#replace -1 with false

dc["easy_apply"] =dc["easy_apply"].astype(str)
dc.easy_apply=[x.replace("-1","False") for x in dc.easy_apply]
dc.easy_apply=[x.upper() for x in dc.easy_apply]
dc

    age  salary rating       location established easy_apply
0    44   44-99    5.4       India,In        1999       TRUE
1    66   55-66    3.5    New York,Ny        2002       TRUE
2    39   77-89    0.0    New York,Ny     Unknown      FALSE
3    64   44-99    4.4       India In        1988      FALSE
4    25   44-99    6.4  Australia Aus        2002      FALSE
5    44   77-89    1.4       India,In        1999       TRUE
6    21   44-99    0.0    New York,Ny     Unknown      FALSE
7    44   44-99    0.0  Australia Aus     Unknown      FALSE
8    35   44-99    5.4    New York,Ny     Unknown      FALSE
9    22   44-99    7.7       India,In     Unknown       TRUE
10   55   10-49    5.4       India,In        2008       TRUE
11   44   10-49    6.7       India,In        2009      FALSE
12   39   44-99    0.0       India,In        1999      FALSE
13   25   44-99    0.0  Australia Aus        2019       TRUE
14   66   44-99    4.0  Australia Aus        2020       TRUE
15   44  88-101    3.0  Australia Aus        1999      FALSE
16   19   19-40    4.5       India,In        1984      FALSE
17   39   44-99    5.3    New York,Ny        1943       TRUE
18   35   44-99    6.7    New York,Ny        1954       TRUE
19   32   44-99    3.3    New York,Ny        1955       TRUE
20   39   44-99    5.7    New York,Ny        1944       TRUE
21   35   44-99    5.0    New York,Ny        1946      FALSE
22   19   55-66    7.8    New York,Ny        1988       TRUE
23   39   44-99    2.4    New York,Ny        1999       TRUE
24   13   44-99    0.0    New York,Ny        1987      FALSE
25   55   44-99    0.0  Australia Aus        1980       TRUE
26   39   55-66    Nil       India,In        1934       TRUE
27   52   44-99    5.4       India,In        1935      FALSE
28   39   39-88    3.4  Australia Aus        1932      FALSE

**week 3 dataset-2**

In [ ]:
ch = pd.read_csv("/content/chipotle.tsv",sep='\t')
ch

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
copy_data2=ch.copy()

In [ ]:
#missing values
ch.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
#duplicated entries
ch.duplicated(subset=None, keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
4617    False
4618    False
4619    False
4620    False
4621    False
Length: 4622, dtype: bool

In [ ]:
ch.choice_description=ch.choice_description.replace(np.nan,"Nil")
ch.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,Nil,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,Nil,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

sample=ch.choice_description.str.split(",",expand=True)
sample

In [ ]:
ch.item_price=[x.replace("$","") for x in ch.item_price]
ch.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,Nil,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,Nil,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [ ]:
#Quantity of each item? (Top 5 itmes available in store)

sample=ch.groupby(["item_name"])["quantity"].sum().sort_values(ascending=False)
print(sample)
print("\n")
sample_1=sample.sort_values(ascending=False).head()
print(sample_1)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chips and Tomatillo Red Chili Salsa       50
Chicken Crispy Tacos                      50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Veggie Salad                               6
Carnitas Salad Bowl                        6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Chips and Mild Fresh Tomato Salsa          1
Carnitas Salad                             1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64


item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [ ]:
#which is most ordered item in choice_description?

des=ch.groupby(["choice_description"])["quantity"].sum()
des1=des.sort_values(ascending=False).head(2)

des1.iloc[1:2 :]

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

In [ ]:
#What is total order count?

order=ch.groupby(["order_id"]).sum()
order.tail(1)

<ipython-input-11-d115abeb54af>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  order=ch.groupby(["order_id"]).sum()

          quantity
order_id
1834             3

In [ ]:
#What is revenue in dollars?

ch["item_price"]=ch["item_price"].astype(float)
ch.item_price.sum()

34500.16

In [ ]:
#what are number of orders?

order=ch.groupby(["order_id"]).sum()
order

<ipython-input-13-e3d3078f2eb2>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  order=ch.groupby(["order_id"]).sum()

          quantity  item_price
order_id
1                4       11.56
2                2       16.98
3                2       12.67
4                2       21.00
5                2       13.70
...            ...         ...
1830             2       23.00
1831             3       12.90
1832             2       13.20
1833             2       23.50
1834             3       28.75

[1834 rows x 2 columns]

In [ ]:
ch.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,Nil,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,Nil,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [ ]:
#What is average revenue amount per order?

amt=ch.groupby(["order_id"])["item_price"].mean().round(decimals=2)
amt

order_id
1        2.89
2       16.98
3        6.34
4       10.50
5        6.85
        ...
1830    11.50
1831     4.30
1832     6.60
1833    11.75
1834     9.58
Name: item_price, Length: 1834, dtype: float64

In [ ]:
#How many different items are sold?

items=ch.groupby(["item_name"])["quantity"].sum().sort_values(ascending=False)
items.reset_index()

                                item_name  quantity
0                            Chicken Bowl       761
1                         Chicken Burrito       591
2                     Chips and Guacamole       506
3                           Steak Burrito       386
4                       Canned Soft Drink       351
5                                   Chips       230
6                              Steak Bowl       221
7                           Bottled Water       211
8            Chips and Fresh Tomato Salsa       130
9                             Canned Soda       126
10                     Chicken Salad Bowl       123
11                     Chicken Soft Tacos       120
12                          Side of Chips       110
13                         Veggie Burrito        97
14                       Barbacoa Burrito        91
15                            Veggie Bowl        87
16                          Carnitas Bowl        71
17                          Barbacoa Bowl        66
18                       Carnitas Burrito        60
19                       Steak Soft Tacos        56
20                      6 Pack Soft Drink        55
21    Chips and Tomatillo Red Chili Salsa        50
22                   Chicken Crispy Tacos        50
23  Chips and Tomatillo Green Chili Salsa        45
24                    Carnitas Soft Tacos        40
25                     Steak Crispy Tacos        36
26  Chips and Tomatillo-Green Chili Salsa        33
27                       Steak Salad Bowl        31
28                       Nantucket Nectar        29
29    Chips and Tomatillo-Red Chili Salsa        25
30                    Barbacoa Soft Tacos        25
31     Chips and Roasted Chili Corn Salsa        23
32                                   Izze        20
33                      Veggie Salad Bowl        18
34     Chips and Roasted Chili-Corn Salsa        18
35                  Barbacoa Crispy Tacos        12
36                    Barbacoa Salad Bowl        10
37                          Chicken Salad         9
38                  Carnitas Crispy Tacos         8
39                      Veggie Soft Tacos         8
40                                Burrito         6
41                           Veggie Salad         6
42                    Carnitas Salad Bowl         6
43                                   Bowl         4
44                            Steak Salad         4
45                                  Salad         2
46                           Crispy Tacos         2
47      Chips and Mild Fresh Tomato Salsa         1
48                         Carnitas Salad         1
49                    Veggie Crispy Tacos         1

In [ ]:
#what is revenue from each product?
#in dollars

prod=ch.groupby(["item_name"])["item_price"].sum().sort_values(ascending=False)
prod.reset_index()

                                item_name  item_price
0                            Chicken Bowl     7342.73
1                         Chicken Burrito     5575.82
2                           Steak Burrito     3851.43
3                              Steak Bowl     2260.19
4                     Chips and Guacamole     2201.04
5                      Chicken Salad Bowl     1228.75
6                      Chicken Soft Tacos     1108.09
7                          Veggie Burrito      934.77
8                        Barbacoa Burrito      894.75
9                             Veggie Bowl      867.99
10                          Carnitas Bowl      736.71
11                          Barbacoa Bowl      672.36
12                       Carnitas Burrito      597.83
13                       Steak Soft Tacos      536.05
14                                  Chips      494.34
15                   Chicken Crispy Tacos      472.13
16                      Canned Soft Drink      438.75
17                    Carnitas Soft Tacos      375.94
18           Chips and Fresh Tomato Salsa      361.36
19                     Steak Crispy Tacos      357.34
20                      6 Pack Soft Drink      356.95
21                       Steak Salad Bowl      343.59
22                          Bottled Water      302.56
23                    Barbacoa Soft Tacos      250.46
24                          Side of Chips      185.90
25                      Veggie Salad Bowl      182.50
26    Chips and Tomatillo Red Chili Salsa      147.50
27                            Canned Soda      137.34
28  Chips and Tomatillo Green Chili Salsa      132.75
29                  Barbacoa Crispy Tacos      120.21
30                    Barbacoa Salad Bowl      106.40
31                       Nantucket Nectar       98.31
32                          Chicken Salad       81.09
33  Chips and Tomatillo-Green Chili Salsa       78.87
34                  Carnitas Crispy Tacos       77.96
35                      Veggie Soft Tacos       73.96
36     Chips and Roasted Chili Corn Salsa       67.85
37                                   Izze       67.80
38                    Carnitas Salad Bowl       66.34
39    Chips and Tomatillo-Red Chili Salsa       59.75
40                           Veggie Salad       50.94
41                                Burrito       44.40
42     Chips and Roasted Chili-Corn Salsa       43.02
43                            Steak Salad       35.66
44                                   Bowl       29.60
45                                  Salad       14.80
46                           Crispy Tacos       14.80
47                         Carnitas Salad        8.99
48                    Veggie Crispy Tacos        8.49
49      Chips and Mild Fresh Tomato Salsa        3.00

In [ ]:
#Find the unique items

u_items=ch.item_name.unique()
pd.value_counts(u_items)

Chips and Fresh Tomato Salsa             1
Bowl                                     1
Barbacoa Crispy Tacos                    1
Veggie Salad Bowl                        1
Chips and Roasted Chili-Corn Salsa       1
Chips and Roasted Chili Corn Salsa       1
Carnitas Soft Tacos                      1
Chicken Salad                            1
Canned Soft Drink                        1
Steak Salad Bowl                         1
6 Pack Soft Drink                        1
Chips and Tomatillo-Red Chili Salsa      1
Burrito                                  1
Izze                                     1
Crispy Tacos                             1
Carnitas Crispy Tacos                    1
Steak Salad                              1
Chips and Mild Fresh Tomato Salsa        1
Veggie Soft Tacos                        1
Carnitas Salad Bowl                      1
Barbacoa Salad Bowl                      1
Salad                                    1
Veggie Crispy Tacos                      1
Veggie Salad                             1
Chips and Tomatillo Red Chili Salsa      1
Steak Crispy Tacos                       1
Veggie Bowl                              1
Veggie Burrito                           1
Nantucket Nectar                         1
Chips and Tomatillo-Green Chili Salsa    1
Chicken Bowl                             1
Side of Chips                            1
Steak Burrito                            1
Steak Soft Tacos                         1
Chips and Guacamole                      1
Chicken Crispy Tacos                     1
Chicken Soft Tacos                       1
Chicken Burrito                          1
Canned Soda                              1
Barbacoa Burrito                         1
Carnitas Burrito                         1
Carnitas Bowl                            1
Bottled Water                            1
Chips and Tomatillo Green Chili Salsa    1
Barbacoa Bowl                            1
Chips                                    1
Chicken Salad Bowl                       1
Steak Bowl                               1
Barbacoa Soft Tacos                      1
Carnitas Salad                           1
dtype: int64

In [ ]:
#Find total cost and quantity of every unique items

u_items=ch.item_name.unique()
pd.value_counts(u_items).reset_index()

                                    index  0
0            Chips and Fresh Tomato Salsa  1
1                                    Bowl  1
2                   Barbacoa Crispy Tacos  1
3                       Veggie Salad Bowl  1
4      Chips and Roasted Chili-Corn Salsa  1
5      Chips and Roasted Chili Corn Salsa  1
6                     Carnitas Soft Tacos  1
7                           Chicken Salad  1
8                       Canned Soft Drink  1
9                        Steak Salad Bowl  1
10                      6 Pack Soft Drink  1
11    Chips and Tomatillo-Red Chili Salsa  1
12                                Burrito  1
13                                   Izze  1
14                           Crispy Tacos  1
15                  Carnitas Crispy Tacos  1
16                            Steak Salad  1
17      Chips and Mild Fresh Tomato Salsa  1
18                      Veggie Soft Tacos  1
19                    Carnitas Salad Bowl  1
20                    Barbacoa Salad Bowl  1
21                                  Salad  1
22                    Veggie Crispy Tacos  1
23                           Veggie Salad  1
24    Chips and Tomatillo Red Chili Salsa  1
25                     Steak Crispy Tacos  1
26                            Veggie Bowl  1
27                         Veggie Burrito  1
28                       Nantucket Nectar  1
29  Chips and Tomatillo-Green Chili Salsa  1
30                           Chicken Bowl  1
31                          Side of Chips  1
32                          Steak Burrito  1
33                       Steak Soft Tacos  1
34                    Chips and Guacamole  1
35                   Chicken Crispy Tacos  1
36                     Chicken Soft Tacos  1
37                        Chicken Burrito  1
38                            Canned Soda  1
39                       Barbacoa Burrito  1
40                       Carnitas Burrito  1
41                          Carnitas Bowl  1
42                          Bottled Water  1
43  Chips and Tomatillo Green Chili Salsa  1
44                          Barbacoa Bowl  1
45                                  Chips  1
46                     Chicken Salad Bowl  1
47                             Steak Bowl  1
48                    Barbacoa Soft Tacos  1
49                         Carnitas Salad  1